name: TelerikAcademy Web_Forum CI / CD
on:
  workflow_dispatch:
jobs:
  initial_testing:
    runs-on: self-hosted
    steps:
      # Commenting out this changes, for the moment to see if things will run normally:
      # - name: Checkout repository
      #   uses: actions/checkout@v4
      - name: Run Gradle Unit Tests
        run: |
          ./gradlew test
